---
influx:
  build: ./influxdb
  ports:
    - 8083:8083
    - 8086:8086
  environment:
    - PRE_CREATE_DB=telegraf

telegraf:
  build: ./telegraf
  links:
    - influx

grafana:
  image: grafana/grafana:2.5.0
  ports:
    - 3000:3000
